### ISSUE TITLE
[BUG] Avoid operations in loop

### ISSUE THREAD

**Issue by rubicn** [forcedotcom/sfdx-code-analyzer-vscode#13]
**Describe the bug**
For loop with inner class SOQL not showing "Avoid operations in loops"

**To Reproduce**
Create 2 classes with 2 methods for each one of them 
one with a for loop that calling the other class method.
The other class method should return a SOQL List.
![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/55830438/11fba764-00d7-493a-a9f2-5bcc4eddf088)
![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/55830438/86f21ab8-9b86-4c60-8d38-3d9f75ec5b20)

**Expected behavior**
  should get a warning "Avoid operations in loops that may hit governor limits"

**Comment by jfeingold35** [comment]
@rubicn , which command are you running, and do you have a code snippet that can reproduce?

**Comment by rubicn** [comment]
> @rubicn , which command are you running, and do you have a code snippet that can reproduce?
![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/55830438/52aa97d8-c35a-4dd4-a91c-49b110746093)

![image](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/55830438/9566d5a5-724c-4cf0-b39b-3a5860843e8c)

**Comment by jfeingold35** [comment]
@rubicn , I'm confused. Are you running this through the VSCode Extension's right-click commands, or via the CLI directly?

**Comment by rubicn** [comment]
this is the same, isn't it?

**Comment by jfeingold35** [comment]
@rubicn , the two VSCode command correspond to different CLI commands.
The "...with Code Analyzer" one is equivalent to doing `sfdx scanner:run`, while the "...with Graph-Engine path-based analysis" is equivalent to `sfdx scanner:run:dfa`.
So if you're using the extension, then it matters which right-click command you're using.
And if you're not using the extension but are instead running directly through the CLI, it would be best if you could create the issue on the [repo for the scanner itself](https://github.com/forcedotcom/sfdx-scanner/issues) instead of here, in order to keep paper trails clean

**Comment by rubicn** [comment]
I'm using the extension,  right-click the command still it doesn't hit the "Avoid operations in loops" in that case.

**Comment by jfeingold35** [comment]
@rubicn , I still need to know _which_ right-click command you're using. The "Scan with Code Analyzer" one or the "Scan with Graph-Engine path-based analysis" one?

**Comment by rubicn** [comment]
Scan with Code Analyzer

**Comment by jfeingold35** [comment]
@rubicn , thanks for clarifying, and thanks for logging this on the Scanner repo as [#1182](https://github.com/forcedotcom/sfdx-scanner/issues/1182). Please see my response on that Issue for an explanation of why this is working as expected.
