### ISSUE TITLE
Extension ignores custom Apex/XML rules from Ruleset.xml

### ISSUE THREAD

**Issue by rsoesemann** [forcedotcom/sfdx-code-analyzer-vscode#15]
I am currently using [Apex PMD VS Code extension by Charlie Jonas](https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-pmd) which soon might be [migrated and maintained by the PMD community](https://github.com/ChuckJonas/vscode-apex-pmd/issues/133).

Every [PMD user relies on Custom XPath rules for Apex and arbitrary XML metadata](https://docs.google.com/presentation/d/1t8LokITTGUEnAwf0-bJSLbMgXS6-F19_-eAMmOfN1OA/edit?usp=sharing) and the Plugin mostly supports that.
![Screenshot_2023-09-19_at_10_50_29](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/8180281/6138c878-c276-4bd8-8959-1f828b9d59e9)

I could NOT get the VS Code Extension to work with the same Ruleset:
https://github.com/rsoesemann/unhappy-soup/blob/master/pmd/ruleset.xml
![Screenshot_2023-09-19_at_10_53_34](https://github.com/forcedotcom/sfdx-code-analyzer-vscode/assets/8180281/304ed6ee-23a4-426c-9a78-28ae252fb644)

**Comment by jfeingold35** [comment]
@rsoesemann , thanks for bringing this to our attention. I'll look into it and see if I can figure out what's going on.
In the meantime, have you tried using that same config file as the value for `--pmdconfig` in a `scanner:run` invocation? The "PMD: Custom Config File" setting is basically a wrapper around the `--pmdconfig` flag, so if the file works for the flag then it should work for the setting.

**Comment by jfeingold35** [comment]
@rsoesemann , you mentioned that you're still experiencing this problem in the VSCode extension, but I can't reproduce.
I did the following:
`sfdx scanner:rule:add --language xml --path "./Users/jfeingold/Code/unhappy-soup/pmd/category/xml/custom.xml"`, which succeeded.
Then I ran `sfdx scanner:rule:list --language xml` and observed that the new rules had been added.
And finally I was able to use the "SFDX: Scan current file with Code Analyzer" right-click option in this file:
```
<?xml version="1.0" encoding="UTF-8"?>
<CustomField xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>Bad_Name__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Lorem Ipsum.</description>
    <externalId>false</externalId>
    <inlineHelpText>Lorem Ipsum</inlineHelpText>
    <label>Active</label>
    <trackTrending>false</trackTrending>
    <type>Checkbox</type>
</CustomField>
```
And that gave me violations for, among other things, your `NoUnderscoresInFieldNames` rule.

**Comment by rsoesemann** [comment]
@jfeingold35 
1. To have Apex PMD find Custom Rule issues I need to in the settings tell it where my single consolidated ruleset.xml is and it finds ALL issues.
2. Currently it looks like the updated CLI Scanner also sees all rules and finds issues when I call a single command sfdx `scanner:run --format table --target force-app --engine "pmd" --pmdconfig "ruleset.xml"`
3. I expect that same thing to work when I click the Run Scanner command on file. No separate files, no registering rules, no explicitly setting languages

**Comment by jfeingold35** [comment]
@rsoesemann , I understand that you have certain expectations based on your experience with the Apex PMD extension. Please understand that the VSCode extension is currently in beta. It is not finished. We are actively working on it, and many elements of the UI and UX may change between now and the 1.0 release.

As previously explained, in the scanner, one uses `scanner:rule:add` to add custom rules to our catalog and run them alongside the default ones, and one uses `--pmdconfig` to replace our catalog with an XML of their choice.

At this time, the extension has no equivalent of `scanner:rule:add`, so that command must be invoked directly through the CLI. I apologize for the inconvenience, but that's simply the current fact of the matter.

The extension's equivalent of the `--pmdconfig` file is the "Code Analyzer > PMD: Custom Config File" setting.
